"""update sudah vaksin

Revision ID: ac11b06a8ea6
Revises: ac6e8a4cdbfb
Create Date: 2021-07-21 16:49:33.629603

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac11b06a8ea6'
down_revision = 'ac6e8a4cdbfb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta_vaksinasi', sa.Column('sudah_vaksin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peserta_vaksinasi', 'sudah_vaksin')
    # ### end Alembic commands ###
