"""update user

Revision ID: ac6e8a4cdbfb
Revises: bb1257b6edc4
Create Date: 2021-07-15 21:43:04.962032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac6e8a4cdbfb'
down_revision = 'bb1257b6edc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta_vaksinasi', sa.Column('jenis_pekerjaan', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peserta_vaksinasi', 'jenis_pekerjaan')
    # ### end Alembic commands ###
