"""update user

Revision ID: c32d3f8d33b9
Revises: 0b4971528a81
Create Date: 2021-07-15 11:59:51.797249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c32d3f8d33b9'
down_revision = '0b4971528a81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta_vaksinasi', sa.Column('waktu_vaksin', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peserta_vaksinasi', 'waktu_vaksin')
    # ### end Alembic commands ###
