"""update peserta vaksinasi

Revision ID: c3cde436ed3c
Revises: f750d1baa547
Create Date: 2021-07-14 23:15:34.973327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cde436ed3c'
down_revision = 'f750d1baa547'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta_vaksinasi', sa.Column('umur', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peserta_vaksinasi', 'umur')
    # ### end Alembic commands ###
