"""update peserta vaksinasi

Revision ID: d5ea9567d2a5
Revises: c3cde436ed3c
Create Date: 2021-07-14 23:20:23.023982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5ea9567d2a5'
down_revision = 'c3cde436ed3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('peserta_vaksinasi', sa.Column('penyelenggara', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('peserta_vaksinasi', 'penyelenggara')
    # ### end Alembic commands ###
