"""peserta vaksinasi

Revision ID: f750d1baa547
Revises: 37f06a334dbf
Create Date: 2021-07-14 22:44:11.212280

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f750d1baa547'
down_revision = '37f06a334dbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('peserta_vaksinasi',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sa.String(length=140), nullable=True),
    sa.Column('pn', sa.String(length=140), nullable=True),
    sa.Column('unit_kerja', sa.String(length=140), nullable=True),
    sa.Column('batch', sa.String(length=140), nullable=True),
    sa.Column('nik', sa.String(length=140), nullable=True),
    sa.Column('nama_lengkap', sa.String(length=140), nullable=True),
    sa.Column('jenis_kelamin', sa.String(length=140), nullable=True),
    sa.Column('tanggal_lahir', sa.String(length=140), nullable=True),
    sa.Column('instansi_pekerjaan', sa.String(length=140), nullable=True),
    sa.Column('pekerjaan', sa.String(length=140), nullable=True),
    sa.Column('no_hp', sa.String(length=140), nullable=True),
    sa.Column('alamat_ktp', sa.String(length=140), nullable=True),
    sa.Column('kode_kabupaten', sa.String(length=140), nullable=True),
    sa.Column('nama_kota', sa.String(length=140), nullable=True),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('waktu_kehadiran', sa.DateTime(), nullable=True),
    sa.Column('hadir', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_peserta_vaksinasi_timestamp'), 'peserta_vaksinasi', ['timestamp'], unique=False)
    op.create_index(op.f('ix_peserta_vaksinasi_waktu_kehadiran'), 'peserta_vaksinasi', ['waktu_kehadiran'], unique=False)
    op.add_column('user', sa.Column('unit_kerja', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'unit_kerja')
    op.drop_index(op.f('ix_peserta_vaksinasi_waktu_kehadiran'), table_name='peserta_vaksinasi')
    op.drop_index(op.f('ix_peserta_vaksinasi_timestamp'), table_name='peserta_vaksinasi')
    op.drop_table('peserta_vaksinasi')
    # ### end Alembic commands ###
